### ISSUE TITLE
Segfault on Fedora 29 when tuned to DAB station

### ISSUE THREAD

**Issue by yarda** [andrmuel/gr-dab#20]
Versions used:
```
gr-dab-0.3
gnuradio-3.7.13.5
boost-1.66.0
```
I ran:
```
grdab adjust
```

Tuned to 229.072, where the local DAB transmitter is and the grdab immediately crashed. This is 100% reproducible. I Tried to tune to Brno Hady (12D channel) in Czech Republic. Backtrace:

```
#0  0x00007fddd6d1057f in raise () at /lib64/libc.so.6
#1  0x00007fddd6cfa895 in abort () at /lib64/libc.so.6
#2  0x00007fddcf984868 in std::__replacement_assert(char const*, int, char const*, char const*)
    (__file=__file@entry=0x7fddcf9ad058 "/usr/include/c++/8/bits/stl_vector.h", __line=__line@entry=932, __function=__function@entry=0x7fddcf9b2960 <_ZZNSt6vectorIPKvSaIS1_EEixEmE19__PRETTY_FUNCTION__> "std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = const void*; _Alloc = std::allocator<const void*>; std::vector<_Tp, _Alloc>::r"..., __condition=__condition@entry=0x7fddcf9ad028 "__builtin_expect(__n < this->size(), true)") at /usr/include/c++/8/x86_64-redhat-linux/bits/c++config.h:2391
#3  0x00007fddcf992ae5 in std::vector<void const*, std::allocator<void const*> >::operator[](unsigned long) (__n=1, this=<optimized out>)
    at /usr/src/debug/gr-dab-0.3-1.fc29.x86_64/lib/magnitude_equalizer_vcc_impl.cc:108
#4  0x00007fddcf992ae5 in gr::dab::magnitude_equalizer_vcc_impl::work(int, std::vector<void const*, std::allocator<void const*> >&, std::vector<void*, std::allocator<void*> >&)
    (this=<optimized out>, noutput_items=1, input_items=..., output_items=...) at /usr/src/debug/gr-dab-0.3-1.fc29.x86_64/lib/magnitude_equalizer_vcc_impl.cc:95
#5  0x00007fddcf90d5bb in gr::sync_block::general_work(int, std::vector<int, std::allocator<int> >&, std::vector<void const*, std::allocator<void const*> >&, std::vector<void*, std::allocator<void*> >&) (this=0x56278ed23f80, noutput_items=<optimized out>, ninput_items=..., input_items=..., output_items=...)
    at /usr/src/debug/gnuradio-3.7.13.5-1.fc29.x86_64/gnuradio-runtime/lib/sync_block.cc:66
#6  0x00007fddcf8d3457 in gr::block_executor::run_one_iteration() (this=this@entry=0x7fdd4effcd40)
    at /usr/src/debug/gnuradio-3.7.13.5-1.fc29.x86_64/gnuradio-runtime/lib/block_executor.cc:473
#7  0x00007fddcf916ecd in gr::tpb_thread_body::tpb_thread_body(boost::shared_ptr<gr::block>, boost::shared_ptr<boost::barrier>, int)
    (this=0x7fdd4effcd40, block=..., start_sync=..., max_noutput_items=<optimized out>) at /usr/src/debug/gnuradio-3.7.13.5-1.fc29.x86_64/gnuradio-runtime/lib/tpb_thread_body.cc:123
#8  0x00007fddcf908db8 in gr::tpb_container::operator()() (this=0x5627919b4090) at /usr/include/c++/8/bits/atomic_base.h:512
#9  0x00007fddcf908db8 in gr::thread::thread_body_wrapper<gr::tpb_container>::operator()() (this=0x5627919b4090)
    at /usr/src/debug/gnuradio-3.7.13.5-1.fc29.x86_64/gnuradio-runtime/include/gnuradio/thread/thread_body_wrapper.h:51
#10 0x00007fddcf908db8 in boost::detail::function::void_function_obj_invoker0<gr::thread::thread_body_wrapper<gr::tpb_container>, void>::invoke(boost::detail::function::function_buffer&)
    (function_obj_ptr=...) at /usr/include/boost/function/function_template.hpp:159
#11 0x00007fddcf8bcdf6 in boost::function0<void>::operator()() const (this=<optimized out>) at /usr/include/boost/function/function_template.hpp:673
#12 0x00007fddcf8bcdf6 in boost::detail::thread_data<boost::function0<void> >::run() (this=<optimized out>) at /usr/include/boost/thread/detail/thread.hpp:116
#13 0x00007fddcf11f671 in thread_proxy () at /lib64/libboost_thread.so.1.66.0
#14 0x00007fddd703558e in start_thread () at /lib64/libpthread.so.0
#15 0x00007fddd6dd56f3 in clone () at /lib64/libc.so.6
```

Without DAB signal it works, i.e. runs and not crashes.

The grdab tests seems all to pass:
```
Running tests...
/usr/bin/ctest --force-new-ctest-process 
Test project /builddir/build/BUILD/gr-dab-0.3/build
      Start  1: test_dab
 1/14 Test  #1: test_dab .........................   Passed    0.04 sec
      Start  2: qa_time_deinterleave_ff
 2/14 Test  #2: qa_time_deinterleave_ff ..........   Passed    0.63 sec
      Start  3: qa_fib_sink_vb
 3/14 Test  #3: qa_fib_sink_vb ...................   Passed    0.52 sec
      Start  4: qa_crc16_bb
 4/14 Test  #4: qa_crc16_bb ......................   Passed    0.54 sec
      Start  5: qa_select_subch_vfvf
 5/14 Test  #5: qa_select_subch_vfvf .............   Passed    0.53 sec
      Start  6: qa_unpuncture_ff
 6/14 Test  #6: qa_unpuncture_ff .................   Passed    0.54 sec
      Start  7: qa_prune
 7/14 Test  #7: qa_prune .........................   Passed    0.54 sec
      Start  8: qa_puncture_bb
 8/14 Test  #8: qa_puncture_bb ...................   Passed    0.54 sec
      Start  9: qa_mp2_decode_bs
 9/14 Test  #9: qa_mp2_decode_bs .................   Passed    0.53 sec
      Start 10: qa_mp4_decode_bs
10/14 Test #10: qa_mp4_decode_bs .................   Passed    0.75 sec
      Start 11: qa_dabplus_audio_decoder_ff
11/14 Test #11: qa_dabplus_audio_decoder_ff ......   Passed    0.56 sec
      Start 12: qa_reed_solomon_decode_bb
12/14 Test #12: qa_reed_solomon_decode_bb ........   Passed    0.64 sec
      Start 13: qa_valve_ff
13/14 Test #13: qa_valve_ff ......................   Passed    0.57 sec
      Start 14: qa_peak_detector_fb
14/14 Test #14: qa_peak_detector_fb ..............   Passed    0.57 sec

100% tests passed, 0 tests failed out of 14

Total Test time (real) =   7.53 sec
```

**Comment by yarda** [comment]
It seems that with lowered gain it doesn't crash - I dropped the gain from the default 50 to 20 and no more crashes, but unfortunately now there is no signal received. Currently, I am not sure whether it crashes due to high gain or whether it crashes just when it sees some useful signal. I will try to observe with better antenna. The problem doesn't seem to be HW related - I tried with different RTL2832 sticks (with different tuners) and the result was the same - crash.

**Comment by yarda** [comment]
It crashes where there is usable DAB signal - it crashed with good antenna and gain set to 0.

**Comment by andrmuel** [comment]
Thanks for the report. I'm currently not actively maintaining this project though, so no promises. Pull requests are always welcome.

**Comment by rubund** [comment]
@yarda  You may try again after I pushed this commit: https://github.com/andrmuel/gr-dab/commit/aeb8a6e2c9a000a3dcdb71500fc668534a12a1d2

**Comment by yarda** [comment]
@rubund  thanks, I will check, sorry for delay. But I think the problem I was encountering was primarily caused by problem in my gnuradio.

**Comment by yarda** [comment]
This is no more problem.
